### ISSUE TITLE
Cannot run index

### ISSUE THREAD

**Issue by chrisfield490** [Ellerhold/fs2es-indexer#1]
When i run fs2es-indexer index i get the below error on my ubuntu 20.04 LTS server:
 **  File "/usr/local/bin/fs2es-indexer", line 4, in <module>
    __import__('pkg_resources').run_script('fs2es-indexer==0.3.0', 'fs2es-indexer')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/fs2es_indexer-0.3.0-py3.8.egg/EGG-INFO/scripts/fs2es-indexer", line 43, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/etc/fs2es-indexer/config.yml' **

and my config directory is set as - "/my-directory"

Any help or info is greatly appreciated

**Comment by elfranne** [comment]
The error is that python tries to open the default config file, so it seems the config option is not set properly.
What command are you using ? The correct command should be something like `fs2es-indexer --config /path/to/config.yml index`

**Comment by chrisfield490** [comment]
Amazing, thank you. I knew I had to be doing something wrong. I can see now it is indexing my files.

**Comment by MatthiasKuehneEllerhold** [comment]
Nice :)
