### ISSUE TITLE
a few errors

### ISSUE THREAD

**Issue by ra1nb0w** [Ellerhold/fs2es-indexer#12]
Hi,
first of all thank you very much for your work!
I have two troubles:
- when I search I get the following error
```
2022-03-11 13:07:25 Failed to search for documents of index "files" at elasticsearch "http://localhost:9200": search() got an unexpected keyword argument 'query'
```
with command
```
fs2es-indexer search --log-level-es DEBUG --search-path /home/rainbow --search-file "AR9280.pdf"
```
- during index
```
2022-03-11 12:42:31 Reading config file "/etc/fs2es-indexer/config.yml"
2022-03-11 12:42:31 - Creating index "files" ...
2022-03-11 12:42:32 - Index "files" successfully created
2022-03-11 12:42:32 - Indexing of files and directories in "/data/media" ...
Traceback (most recent call last):
  File "/usr/bin/fs2es-indexer", line 4, in <module>
    __import__('pkg_resources').run_script('fs2es-indexer==0.3.3', 'fs2es-indexer')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3/dist-packages/fs2es_indexer-0.3.3-py3.9.egg/EGG-INFO/scripts/fs2es-indexer", line 71, in <module>
  File "/usr/lib/python3/dist-packages/fs2es_indexer-0.3.3-py3.9.egg/fs2es_indexer/Fs2EsIndexer.py", line 186, in index_directories
  File "/usr/lib/python3/dist-packages/fs2es_indexer-0.3.3-py3.9.egg/fs2es_indexer/Fs2EsIndexer.py", line 57, in map_path_to_es_document
  File "/usr/lib/python3.9/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/data/media/software/mac/Labels & Addresses.app/Contents/Frameworks/SBJson.framework/Resources'
```
and the file is a link
```
'/data/media/software/mac/Labels & Addresses.app/Contents/Frameworks/SBJson.framework/Resources' -> Versions/Current/Resources
```
should be checked if it doesn't exist.

Environment:
- Debian 11.2
- fs2es-indexer 99aa62b452432dad65f8c58e25ffb0abf7d2b6f4
- elasticsearch 7.17.1

All with default configuration.

thank you

**Comment by MatthiasKuehneEllerhold** [comment]
Problem 1:
This is really weird, I tested it locally (debian buster with python 3.7.3 and es-lib 7.17.1) and it worked. Ive added the version switcher like I did for all the other calls .. it still works in my setup and SHOULD work in yours now too. 

Problem 2:
This file was deleted between the the `os.walk()` and the `map_path_to_es_document()` ... unlucky I guess. I've added some code to handle this situation.

Please test version 0.3.4 and report back if its fixed or not!

**Comment by ra1nb0w** [comment]
ops. I did now the patch for the second.
```
--- a/fs2es_indexer/Fs2EsIndexer.py
+++ b/fs2es_indexer/Fs2EsIndexer.py
@@ -218,6 +218,8 @@ class Fs2EsIndexer(object):
 
     def path_should_be_indexed(self, path):
         """ Tests if a specific path (dir or file) should be indexed """
+        if os.path.exists(path) is False:
+            return False
         for search_string in self.exclusion_strings:
             if search_string in path:
                 return False
```

**Comment by ra1nb0w** [comment]
with your patch I get
```
2022-03-11 14:09:27 - Files & directories indexed in "/data/media": 2022-03-11 14:09:32 Failed to bulk import documents into elasticsearch "http://localhost:9200": 'NoneType' object has no attribute 'copy'
```
during `index`

**Comment by MatthiasKuehneEllerhold** [comment]
Where does the `copy` come from?!

**Comment by MatthiasKuehneEllerhold** [comment]
Ah sorry

**Comment by ra1nb0w** [comment]
I confirm the first problem is now fixed. thank you!

**Comment by ra1nb0w** [comment]
I am trying the search more. I noticed that with `--search-term "AR9280"` it return one result (correct) but if I use `--search-filename "AR9280.pdf"` no result at all. 
The result is
```
AR9280.pdf: {"path": {"real": "/home/rainbow/documents/Electronics/datasheet/WLAN/AR9280.pdf"}, "file": {"filename": "AR9280.pdf", "filesize": 2148745}, "time": 1647003920.8272278}
```
Am I doing something wrong?

**Comment by MatthiasKuehneEllerhold** [comment]
Try version 0.3.5 now please!

**Comment by ra1nb0w** [comment]
now index works fine

**Comment by ra1nb0w** [comment]
Any idea why I got different results for `--search-term` and `--search-filename`?
Anyway, thank you very much for your fast response now I can enable it in samba and give a try with mdfind

**Comment by MatthiasKuehneEllerhold** [comment]
Spotlight search in samba normally the query used in "search-term", I dont know when exactly the query in "search-filename" is used tbh. Ive implemented both in order to mimic the samba behavior.

I can confirm that search-filename doesnt work for me too. I guess I have to tweak the index mapping somehow?!

**Comment by ra1nb0w** [comment]
ok. Good to know that it is not my system ;-)
Unfortunately, I can't help you since my knowledge about elasticsearch is very poor.
In smb.conf I only need 
```
[global]
        spotlight backend = elasticsearch 
        elasticsearch:address = localhost
        elasticsearch:port = 9200
[homes]
       spotlight = yes
```
Correct?

**Comment by MatthiasKuehneEllerhold** [comment]
Yep

**Comment by ra1nb0w** [comment]
Good. Have a great weekend and thank you very much!

**Comment by ra1nb0w** [comment]
sorry if I bother you again but I have issues on macOS 10.14. Samba `mdsearch` works fine and tcpdump returns good packets when I search a file in Finder Search but no results is shown in the Finder.
```
$ mdutil -s /Volumes/media
/Volumes/media:
	Server search enabled.
```
but
```
mdfind -onlyin /Volumes/media 'test' 
```
is empty.

I have read and re-read the Samba wiki/forum and the C code and I haven't found any suggestion since should work out of the box. Have some suggestion? Should work also in the iPad Finder? Because from that I don't see the elasticsearch request neither.

thanks

**Comment by MatthiasKuehneEllerhold** [comment]
Have you confirmed that the indexer has your file? Try the search feature:
```
fs2es-indexer search --search-path /my/path --search-term "test"
```

If that doesnt work - try rechecking your configuration and / or run the index manually:
```
fs2es-indexer index
```

Is there a file with a name beginning with test (or has words in it beginng with test?) The samba search currently only works by chopping up the filename into words and searches for words beginning with the seaerch term. This is samba behavior and cant be changed in the indexer.

If that DOES work: try checking your smb.conf and the samba logs.

Mac OS 10.14 should work, we've tested 10.13+ ...

**Comment by ra1nb0w** [comment]
Yes. Both `fs2es-indexer search` and `mdsearch` (from samba) are working correctly returning results. They are quantitatively different as you explained. Therefore there is something weird on my macOS. Is there a debug flag on samba for the spotlight part?

**Comment by ra1nb0w** [comment]
Do you know if the finder's search on iPadOS is working with samba spotlight or it is not enabled?

**Comment by MatthiasKuehneEllerhold** [comment]
`fs2es-indexer search` should mimic sambas queries 1:1. Thats what its for. If that works and spotlight doesnt doesnt:

Have you enabled spotlight in your smb.conf? Which version of samba do you use?

You can increase the log level of samba as a whole and of certain subsystems. If you set `log level = 1` you'll get spammed with log entries. But I dont know how the search subsystem is called, maybe something like `mdssvc`? If you find out, please report back and I can add it to the readme.

We havent tested iPadOS, so no clue if it should work or not.

**Comment by ra1nb0w** [comment]
sorry for the delay.
Versions:
- Debian 11
- Samba 4.13.13-Debian
- fs2es-indexer latest commit

Yes, spotlight is enabled in smb.conf and in fact `mdsearch` works fine (tool by samba team to emulate `mdfind`).
`mdssvc` should be the responsible to answer the requests but I don't see anything from log.

**Comment by MatthiasKuehneEllerhold** [comment]
Ive added a whole debugging section to the readme, is this helping you finding the cause?

**Comment by ra1nb0w** [comment]
Thank you very much!
It works fine up to step 5. No result and no log in samba. Maybe something related to samba 4.13 and fixed on samba 4.15? Unfortunately, there is no backport available. To remove any doubt on my macOS installation I will try with another laptop at first chance.

**Comment by MatthiasKuehneEllerhold** [comment]
Youve got the newest 4.13 installed? Weve had it working with 4.12 onwards, we're using Louis repository in debian and it works very good!

In step 3 you found a file but mdfind doesnt? Phew.... errrm idk

**Comment by ra1nb0w** [comment]
I used samba 4.13 from debian main repository. Can you share the Louis repository url?

Yes. Third step with right result but mdfind doesn't return any data. I didn't had the occasion to test another recent macOS installation yet.

**Comment by ra1nb0w** [comment]
Is it https://apt.van-belle.nl/ ? Is it trusted?

**Comment by MatthiasKuehneEllerhold** [comment]
> Is it https://apt.van-belle.nl/ ? Is it trusted?

Yes thats the one I mean.

You have to decide for yourself if you can trust it / him, but this repo is advertised at the samba mailing list without any pushback. We're using it without problems.

**Comment by ra1nb0w** [comment]
Installed but nothing is changed. Surely, something macOS related. I will try with another machine at first chance. thank you
