### ISSUE TITLE
Finder not showing results.

### ISSUE THREAD

**Issue by alexmf23** [Ellerhold/fs2es-indexer#13]
Hey,
I am using Elasticsearch 8.1.2 with the fs3es-crawler on Ubuntu 20.4 for indexing SMB Shares.
I am able to run the indexer and daemon, and i am also able to search with
`fs2es-indexer search --search-path /srv/samba --search-term`

But when i try to search in Finder for a file on the share, it displays 0 results, while SMB logs shows that the files are found.
Do you have maybe an idea about this ? 
Thanks.

**Comment by MatthiasKuehneEllerhold** [comment]
Today I've added some How-To and code in order to make fs2es-indexer work with ESv8. Could you please look into the README.md  and tell me if this is helpful?

**Comment by alexmf23** [comment]
I have looked over your update and installed it. 
I disabled elasticsearch security ( set xpack.security.enabled: false ) for testing without https protocol.
Installation runs without problems, my share was successfully indexed and I can access http://localhost:9200
```
{
  "name" : "node-1",
  "cluster_name" : "ppt4u-cluster",
  "cluster_uuid" : "absXTdHoSZyt7yLg2dkzkw",
  "version" : {
    "number" : "8.1.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "31df9689e80bad366ac20176aa7f2371ea5eb4c1",
    "build_date" : "2022-03-29T21:18:59.991429448Z",
    "build_snapshot" : false,
    "lucene_version" : "9.0.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
```
If i go on `http://localhost:9200/files/_search` it shows me files from inside my share.
The problem comes when i try to search in Finder, it gives me 0 results, while smb_audit log shows files maching my search.

**Comment by MatthiasKuehneEllerhold** [comment]
Support for Elasticsearch was added in Samba 4.12, so 4.13 *should* work!

Did you configure the ES-details correctly in the smb.conf?

What packages are you using - are they self-built without spotlight support?

**Comment by MatthiasKuehneEllerhold** [comment]
So our tests just concluded: Debian 11 Bullseye with ES v8.1.2 with a user for fs2es-indexer and anonymous ro access to the index work.
Our main problem was that data we migrated from a MacOS server had weird metadata in it. Which lead to a crash of the Mac OS finder. In order to fix this we need to
```bash
find . -type f -name ".DS_Store" -delete
find . -exec setfattr -x user.DOSATTRIB {} \;
```

And in your smb.conf
```ini
    veto files = /.DS_Store/
    delete veto files = yes
```

**Comment by MatthiasKuehneEllerhold** [comment]
Ok next step for your debugging: does mdfind in Mac find somethings?

First: mount the samba share
```bash
mdfind -onlyin /Volumes/my-volume/ my-search-term
```

If the first command does not produce anything - wait 5 secs and try again!

**Comment by MatthiasKuehneEllerhold** [comment]
Ive added a whole section on how to debug to the README.md . Please let me know if this is helpful for you!

**Comment by alexmf23** [comment]
> Ive added a whole section on how to debug to the README.md . Please let me know if this is helpful for you!

I have rechecked everything and i found out that mdfind doesnt find any files and i cannot figure it out why.
I have checked samba log and couldnt find any entries with "rpc_server", "mds" or "mdssvc" in it.

**Comment by MatthiasKuehneEllerhold** [comment]
Whats your Mac OS version?
Whats your SMB Protocol Connection version (run `smbutil statshares -a` on your Mac)?

**Comment by MatthiasKuehneEllerhold** [comment]
Your log shows "HTTP connect failed", seems like there is a problem in your ES instance?!

**Comment by MatthiasKuehneEllerhold** [comment]
Sorry, I can't help you there. Try asking the samba mailing list for problem between Samba and ES.
Seems like it is not a problem with the indexer.

If you manage to fix it, please post the solution here so I can add it to the README.
