### ISSUE TITLE
Is there a contributor guide?

### ISSUE THREAD

**Issue by eru** [Ellerhold/fs2es-indexer#15]
(I am not good at English, and I am using an automatic translation, so I apologize if some of the meaning is not clear to you.)

I was allowed to fork the repository some time ago and made some changes, but I didn't even ask this question because I didn't have the time at the time.

There doesn't seem to be a contrib guide or license in the repository, do you accept pull requests?

If so, is there room for the following changes I made to be merged?

- Change mapping settings to be managed in an external file. https://github.com/eru/fs2es-indexer/commit/55f5b7a1f7e4f1855c7b38c95bd4715c31398167
- Change package manager to poetry. https://github.com/eru/fs2es-indexer/commit/2f0bdda4f5a6d0b6bc70db029430aec4fa53276a
- Add tests, linter and formatter.

I look forward to hearing back from you, as I would like to help you in the best way possible.

**Comment by MatthiasKuehneEllerhold** [comment]
Id be happy to review your pull request and merge any improvements or bugfixes!

Please provide 1 pull request for one change so that I can review them individually.

Thanks for your help!
