### ISSUE TITLE
index in background every 30 minutes on server with cronjob or other method?

### ISSUE THREAD

**Issue by chico11mbit** [Ellerhold/fs2es-indexer#18]
Hi,
everything works fine. Thank you for the code.
If I want to index every 30 minutes, do I need to set a cronjob for fs2es-indexer? Or are there other possibilities?
What must the command look like in crontab then? Or must a bash script be written for it?

Best regards
chico

**Comment by MatthiasKuehneEllerhold** [comment]
You can just use "fs2es-indexer daemon" as explained in the readme. Use systemd/initd/etc in order to start this daemon.
