### ISSUE TITLE
changes for Elasticsearch 7

### ISSUE THREAD

**Issue by chico11mbit** [Ellerhold/fs2es-indexer#19]
It works like a charm. There are some issues with elastic search 7 and fs2es-indexer, but i think solved it.

You have to change this in setup.py in the fs2es-indexer folder if you use elastic search 7 :

install_requires=[
'PyYaml',
      **'elasticsearch>=7.0.0,<8.0.0'**

and you have to uncomment in /etc/fs2es-indexer/config.yml :

**library_version: 7**

and in the SMB Global section I have to use:

spotlight backend = elasticsearch
**elasticsearch:address = 127.0.0.1**
elasticsearch:port = 9200

**Comment by MatthiasKuehneEllerhold** [comment]
Ive added your remarks to the README.
