### ISSUE TITLE
No file sizes and wrong change dates

### ISSUE THREAD

**Issue by chico11mbit** [Ellerhold/fs2es-indexer#20]
Hallo,
the search works. But there are a few problems. I don't know if it's the indexer or samba.
The search result in MacOS Finder shows a wrong modification date for each result. e.g. the correct date is 02.04.2004, but it shows 18.11.2006. 17.05.2022 becomes 26.09.2026.

Unfortunately, no file sizes or file types are displayed.

Samba version is 4.13.13-debian

**Comment by MatthiasKuehneEllerhold** [comment]
The return of file sizes & types are not supported in Samba atm (even 4.16).
I think the same goes for the modification date, but it should be displayed as "-". I dont know where the wrong dates are coming from. Do you have a screenshot oder something?

**Comment by chico11mbit** [comment]
Screenshots. One with search result and the other with normal finder view.
![Screenshot](https://user-images.githubusercontent.com/20457815/170954078-34308759-7ca4-40af-89c8-be38e6e0aaa2.png)

**Comment by MatthiasKuehneEllerhold** [comment]
Im seeing the same error now. 

`fs2es-indexer` does not save the change date of the files. IDK where the finder gets them from. This is 99% a samba bug!

**Comment by MatthiasKuehneEllerhold** [comment]
See https://gitlab.com/samba-team/samba/-/blob/master/source3/rpc_server/mdssvc/mdssvc_es.c#L798 for the parsing of the ES-query results. Only path.real is used from the result from ES.
IDK if samba enriches it later with the change date?
