### ISSUE TITLE
Integrate sist2 for full-text search of PDF/epub/DOC/OCR...

### ISSUE THREAD

**Issue by nick008a** [Ellerhold/fs2es-indexer#26]
https://github.com/simon987/sist2

**Comment by MatthiasKuehneEllerhold** [comment]
If you want full-text search and / or OCR please use https://github.com/dadoonet/fscrawler instead. 
This project is intended to be light-weight and without any strain on the machine. OCR or pdf parsing is sadly counter to these goals.
