### ISSUE TITLE
can find with mdfind, but not with finder

### ISSUE THREAD

**Issue by noumenon272** [Ellerhold/fs2es-indexer#28]
I have a dreaded error that gets an "IDK (srsly)" in the readme.

i can find files on my mac with the mdfind command, but when I try to use the finder nothing loads. the only seemingly relevant samba log is:

`[2022/12/17 14:22:37.772005,  3] ../../source3/smbd/smb2_server.c:3953(smbd_smb2_request_error_ex) smbd_smb2_request_error_ex: smbd_smb2_request_error_ex: idx[1] status[NT_STATUS_NOTIFY_CLEANUP] || at ../../source3/smbd/smb2_notify.c:126`

any thoughts on how to correct his?

**Comment by noumenon272** [comment]
update:

its weirder. so search is working in the finder, but not in the current folder. If I click network over to the side it will return the correct search results. However, this means that I can't limit my search to a subfolder, I can only search the entirety of the network.

<img width="1053" alt="Screenshot 2022-12-17 at 11 04 07 AM" src="https://user-images.githubusercontent.com/11728371/208250819-b9472bdb-7513-430d-ac93-b529b50a98cd.png">
<img width="1049" alt="Screenshot 2022-12-17 at 11 03 32 AM" src="https://user-images.githubusercontent.com/11728371/208250820-c77c03f1-94e6-4209-b205-39f68548c99f.png">

**Comment by chico11mbit** [comment]
I can reproduce this behaviour on my Macstudio with MacOS Ventura.

**Comment by Vultilion** [comment]
Same issue here. Tested with bitnami/elasticsearch in docker and various config settings in samba Version 4.13.13-Debian.
Unfortunately it does not work on the ipad at all as it only searches the current folder which does not work on any system so far. Searching the whole network on mac works.
mdfind -onlyin /Volumes/MyShare "searchterm" works perfect.
mdfind -onlyin /Volumes "searchterm" does not work at all.
mdfind "searchterm" also is not finding anything in the network
Very strange, any updates on this?

**Comment by MatthiasKuehneEllerhold** [comment]
I can replicate this bug. 
Mac OS 10.13: the finder search works correctly: my test files is found immediatly.
Mac OS 13.1 Ventura: the finder search does not work: no files found. `mdfind` works though. So ... something changed in between.

Both the same samba server with debian 11 and samba 4.16.

But what I can is this: this is not related to the indexer. Please refer to the samba mailing list (fair chance) or apple support (good luck!!).

**Comment by MatthiasKuehneEllerhold** [comment]
I've emailed Ralph Böhme (a developer of samba itself) and he said that he fixed the problem for another of his customers.
His patch will go upstream "soon" and be available in samba "soon".
