### ISSUE TITLE
Server search not enabled

### ISSUE THREAD

**Issue by hirani89** [Ellerhold/fs2es-indexer#30]
Hi,
I have tried to follow the instructions to my best ability.

`fs2es-indexer search` works on the NAS. but `mdfind -onlyin` does not.

The output of `mdutil -s /Volumes/Shared/` is

```
/System/Volumes/Data/Volumes/Shared:
	Indexing enabled.
```

**Comment by MatthiasKuehneEllerhold** [comment]
Sorry this is not indexer related, therefor closing this issue.

Please look at the README: there is a step-by-step debugging plan to help you. If it still doesnt work we're in "idk" territory. Sorry.
