### ISSUE TITLE
With Elasticsearch Version 8 it does not work.

### ISSUE THREAD

**Issue by emrehayta** [Ellerhold/fs2es-indexer#31]
**Elasticsearch Version: 8.6.2
Samba Version: Version 4.13.13-Debian**

I am not able to get results from my Mac trough Spotlight Search. Creating Index or searching locally on Server with "fs2es-indexer" works.

**I get following errors:**

```
[2023/03/10 12:07:40.667009,  1] ../../source3/rpc_server/mdssvc/srv_mdssvc_nt.c:301(_mdssvc_close)
  _mdssvc_close: invalid handle
[2023/03/10 12:07:50.990174,  0] ../../source4/lib/tls/tls_tstream.c:944(tstream_tls_params_client)
  TLS failed to missing cafile tls/ca.pem - with 'tls verify peer = as_strict_as_possible'
[2023/03/10 12:07:50.990935,  0] ../../source3/rpc_server/mdssvc/mdssvc_es.c:239(mds_es_connect_send)
  mds_es_connect_send: Failed tstream_tls_params_client - NT_STATUS_INVALID_PARAMETER_MIX
[2023/03/10 12:07:50.993717,  0] ../../source3/rpc_server/mdssvc/mdssvc_es.c:156(mds_es_connected)
  mds_es_connected: HTTP connect failed
```

Because Elasticsearch 8 is running with TLS, i have changed the fs2es config to following:

elasticsearch:
  ###The URL of the elasticsearch index
  url: "https://localhost:9200"

Any ideas?

**Comment by MatthiasKuehneEllerhold** [comment]
Does your ES use self-signed certificates? Have you tried the "verify_certs" and / or "ssl_show_warn" in the `config.yml` ?

**Comment by emrehayta** [comment]
Here is the part of my smb.conf for ES

`# elastic + fs2es-indexer
spotlight backend = elasticsearch
elasticsearch:address = localhost
elasticsearch:port = 9200
elasticsearch:use tls = yes

        min protocol = SMB2
        ea support = yes
        vfs objects = catia fruit streams_xattr
        fruit:metadata = stream
        fruit:model = MacSamba
        fruit:posix_rename = yes
        fruit:veto_appledouble = no
        fruit:wipe_intentionally_left_blank_rfork = yes
        fruit:delete_empty_adfiles = yes`

**Comment by MatthiasKuehneEllerhold** [comment]
So you're using self signed certs, that aren't valid for the CAs you have installed in your trust store?

And the indexer refuses to connect to ES because its not using trusted certs.

Either use trusted certs or set `verify_certs` to `false`.
