### ISSUE TITLE
debian also needs python3-setuptools

### ISSUE THREAD

**Issue by lamixer** [Ellerhold/fs2es-indexer#4]
Hello... Thanks for your software, I'm (hopefully) about to get it working to add Spotlight functionality to my Samba shares.

Just a note about your listed dependencies: I'm on Debian 11 (sort of, Proxmox actually) and I had to install python3-setuptools. After that and the others mentioned (python3-yaml was already installed) it set up fine.

**Comment by lamixer** [comment]
also, please re-open issue #2 where I posted a comment, having similar problems.

**Comment by MatthiasKuehneEllerhold** [comment]
Added python3 & -setuptools to the readme. Thanks!
