### ISSUE TITLE
Warnings during `setup.py install`

### ISSUE THREAD

**Issue by slokhorst** [Ellerhold/fs2es-indexer#7]
When running `python3 setup.py install`:
```
running install
/usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
```

Instead using `pip3 install .` seems to work fine.

**Comment by MatthiasKuehneEllerhold** [comment]
Thanks for your issue, Im currently researching on how to change my build process.
Internally we're using another tool to build deb packages - I'll be moving some of it here to consolidate it.

**Comment by MatthiasKuehneEllerhold** [comment]
Ive tried pip install but it doesnt work in Debian buster. Buster uses python 3.7, bullseye 3.9

If anybody knows good resources to learn about forwards and backwards compatible packaging of python programs (incl. dependencies) please hit me up. I havent find anything uptodate that still works in debian buster yet.
