### ISSUE TITLE
Running into Python3 errors on run: Positional arguments can't be used with Elasticsearch API methods.

### ISSUE THREAD

**Issue by macrec-danielvanderwal** [Ellerhold/fs2es-indexer#8]
We try to run the indexer on Rocky Linux but run into this Python errors. Any ideas where this goes wrong? Could it be the new elasticsearch 8.0 is causing this trouble?

[root@ bin]# ./fs2es-indexer daemon
2022-02-01 21:44:07 Reading config file "/etc/fs2es-indexer/config.yml"
2022-02-01 21:44:07 Starting loop of index with a wait time of 5m (= 300 seconds)
Traceback (most recent call last):
  File "./fs2es-indexer", line 4, in <module>
    __import__('pkg_resources').run_script('fs2es-indexer==0.3.0', 'fs2es-indexer')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/fs2es_indexer-0.3.0-py3.6.egg/EGG-INFO/scripts/fs2es-indexer", line 78, in <module>
  File "/usr/local/lib/python3.6/site-packages/fs2es_indexer-0.3.0-py3.6.egg/fs2es_indexer/Fs2EsIndexer.py", line 109, in prepare_index
  File "/usr/local/lib/python3.6/site-packages/elasticsearch-8.0.0b1-py3.6.egg/elasticsearch/_sync/client/utils.py", line 298, in wrapped
    "Positional arguments can't be used with Elasticsearch API methods. "
TypeError: Positional arguments can't be used with Elasticsearch API methods. Instead only use keyword arguments.

NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"

**Comment by MatthiasKuehneEllerhold** [comment]
Im using the elasticsearch library for the connection to ES. Seems like it is not compatible with ES 8.0 yes.

Release notes of the lib: https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/release-notes.html#rn-7-16-3
The state explicit compatibility with 7.16.3 (if using the same client / library version)

**Comment by MatthiasKuehneEllerhold** [comment]
Oh, I see: you're already using the client version 8.0.0b1! Lemme check what I can do! Sadly I cant test my changes... Could you help out pls ?

**Comment by MatthiasKuehneEllerhold** [comment]
I've pushed a commit - can you test it please?

**Comment by macrec-danielvanderwal** [comment]
Sure, thanks Matthias for you commit. I tested and find the following error. It look already far better than before!

[root@ fs2es_indexer]# ./fs2es-indexer daemon

2022-02-02 10:39:53 Reading config file "/etc/fs2es-indexer/config.yml"
2022-02-02 10:39:53 Starting loop of index with a wait time of 5m (= 300 seconds)
/usr/local/lib/python3.6/site-packages/fs2es_indexer-0.3.1-py3.6.egg/fs2es_indexer/Fs2EsIndexer.py:109: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-minimal-setup.html to enable security.
  if self.elasticsearch.indices.exists(index=self.elasticsearch_index):
2022-02-02 10:39:53 - Creating index "files" ...

2022-02-02 10:39:53 Failed to create index at elasticsearch "http://localhost:9200": Couldn't merge 'body' with other parameters as it wasn't a mapping. Instead of using 'body' use individual API parameters

**Comment by macrec-danielvanderwal** [comment]
Thanks for sharing the Link to compatibility information. There I found "Removal of body, params, and other per-request parameters has been delayed beyond 8.0.0. Changed deprecation warnings to mention "future version" instead of 8.0.0." as per above error, I guess a "body" is send.

What makes me wonder, I add the Elasticsearch Repo 7 to Rocky, I'm not sure how I ended up with the 8.x client. I'll take a look into that ;) Thanks again for looking into it!

**Comment by MatthiasKuehneEllerhold** [comment]
tbh Im not so sure how python obtains these libs. e. g. this lib is only available in version 5.4.0 in debian buster, but it installed 7.16.2.
There is another issue that mentions that my installation method (via easy_install) is deprecated. So Ill have to revamp this for sure.

**Comment by hbfs** [comment]
Ran into the same issue. Downgrading the python packages to my elasticsearch version fixed this:
`pip3 list | grep elastic`
elastic-transport    8.0.1
elasticsearch        8.0.0

Show versions available:
`pip3 install elasticsearch==`
...

`pip3 install --upgrade elasticsearch==7.17.0`
`pip3 install --upgrade elastic-transport==7.16.0`

`pip3 list | grep elastic`
elastic-transport    7.16.0
elasticsearch        7.17.0

Suggested fix: Lock versions in setup.py to elasticsearch v7 versions?

**Comment by MatthiasKuehneEllerhold** [comment]
I've set the version constraint of the elasticsearch lib to >=7, <8. So it should work with an ES server v7 and v8.

Ive prepped the upgrade of the lib to v8 with an internal version switch, so it should be easy to switch the lib to v8 once v7 is no more. Lib v8 *cant* access es servers with v7 anymore though!

Please test and reopen this issue if still got problems.

**Comment by macrec-danielvanderwal** [comment]
> Ran into the same issue. Downgrading the python packages to my elasticsearch version fixed this.
Used the same method under Rocky 8
Worked like a charm! [Thanks Sri Gogineni]

@MatthiasKuehneEllerhold I'll test your updates in the next days on a fresh install. Thanks for your ongoing effort and updates!
